//
// HAPServices.hpp
// Homekit
//
//  Generated on: 23.09.2019
//

#ifndef HAPSERVICESBLUETOOTH_HPP_
#define HAPSERVICESBLUETOOTH_HPP_

#include <Arduino.h>

typedef enum {
    HAP_SERVICE_BLUETOOTH_ACCESSORY_INFORMATION     = 0xFED3,
    HAP_SERVICE_BLUETOOTH_CAMERA                    = 0xFEC9,
    HAP_SERVICE_BLUETOOTH_FAN                       = 0xFECB,
    HAP_SERVICE_BLUETOOTH_GARAGE_DOOR_OPENER        = 0xFECE,
    HAP_SERVICE_BLUETOOTH_LIGHT_BULB                = 0xFED2,
    HAP_SERVICE_BLUETOOTH_LOCK_MANAGEMENT           = 0xFECF,
    HAP_SERVICE_BLUETOOTH_LOCK_MECHANISM            = 0xFED0,
    HAP_SERVICE_BLUETOOTH_MICROPHONE                = 0xFEC8,        
    HAP_SERVICE_BLUETOOTH_OUTLET                    = 0xFECC,
    HAP_SERVICE_BLUETOOTH_SPEAKER                   = 0xFEC7,
    HAP_SERVICE_BLUETOOTH_SWITCH                    = 0xFECD,
} HAP_SERVICE_BLUETOOTH;




#endif /* HAPSERVICESBLUETOOTH_HPP_ */
