//
// HAPTLV8.hpp
// Homekit
//
//  Created on: 18.06.2017
//      Author: michael
//

#ifndef HAPTLV8TYPES_HPP_
#define HAPTLV8TYPES_HPP_

#include <Arduino.h>


enum HAP_PAIR_STATE {
	HAP_PAIR_STATE_RESERVED 		= 0x00,
	HAP_PAIR_STATE_M1				= 0x01,
	HAP_PAIR_STATE_M2				= 0x02,
	HAP_PAIR_STATE_M3 				= 0x03,
	HAP_PAIR_STATE_M4				= 0x04,
	HAP_PAIR_STATE_M5				= 0x05,
	HAP_PAIR_STATE_M6				= 0x06,
};

enum HAP_VERIFY_STATE {
	HAP_VERIFY_STATE_RESERVED 		= 0x00,
	HAP_VERIFY_STATE_M1		  		= 0x01,
	HAP_VERIFY_STATE_M2				= 0x02,
	HAP_VERIFY_STATE_M3				= 0x03,
	HAP_VERIFY_STATE_M4				= 0x04,
};


enum HAP_ERROR_TYPE {
	HAP_ERROR_NONE					= 0x00,
	HAP_ERROR_UNKNOWN				= 0x01,
	HAP_ERROR_AUTHENTICATON			= 0x02,
	HAP_ERROR_BACKOFF				= 0x03,
	HAP_ERROR_MAX_PEERS				= 0x04,
	HAP_ERROR_MAX_TRIES				= 0x05,
	HAP_ERROR_UNAVAILABLE			= 0x06,
	HAP_ERROR_BUSY					= 0x07,
};

enum HAP_STATUS_CODE {
	HAP_STATUS_SUCCESS				= 0,
	HAP_STATUS_INUSUFFICIENT_PRIV	= -70401,
	HAP_STATUS_INTERNAL_COMM_ERROR	= -70402,
	HAP_STATUS_BUSY					= -70403,
	HAP_STATUS_READONLY_WRITE		= -70404,
	HAP_STATUS_WRITEONLY_READ		= -70405,
	HAP_STATUS_NO_NOTIFICATION		= -70406,
	HAP_STATUS_OUT_OF_RESSOURCES	= -70407,
	HAP_STATUS_TIMED_OUT			= -70408,
	HAP_STATUS_RESOURCE_NOT_FOUND	= -70409,
	HAP_STATUS_INVALID_VALUE		= -70410,
	HAP_STATUS_AUTH_FAILED			= -70411,
};

enum HAP_TLV_TYPE {
	HAP_TLV_METHOD					= 0x00,
	HAP_TLV_IDENTIFIER				= 0x01,
	HAP_TLV_SALT					= 0x02,
	HAP_TLV_PUBLIC_KEY				= 0x03,
	HAP_TLV_PROOF					= 0x04,
	HAP_TLV_ENCRYPTED_DATA			= 0x05,
	HAP_TLV_STATE					= 0x06,
	HAP_TLV_ERROR					= 0x07,
	HAP_TLV_RETRY_DELAY				= 0x08,
	HAP_TLV_CERTIFICATE				= 0x09,
	HAP_TLV_SIGNATURE				= 0x0A,
	HAP_TLV_PERMISSIONS				= 0x0B,
	HAP_TLV_FRAGMENT_DATA			= 0x0C,
	HAP_TLV_FRAGMENT_LAST			= 0x0D,

	HAP_TLV_SEPERATOR				= 0xFF,
};

enum HAP_TLV_PAIR_TYPE {
	HAP_TLV_PAIR_SETUP				= 0x00,
	HAP_TLV_PAIR_SETUP_AUTH			= 0x01,
	HAP_TLV_PAIR_VERIFY				= 0x02,
	HAP_TLV_PAIR_ADD				= 0x03,
	HAP_TLV_PAIR_REMOVE				= 0x04,
	HAP_TLV_PAIR_LIST				= 0x05
};


#endif /* HAPTLV8TYPES_HPP_ */
