//
// HAPTypes.hpp
// Homekit
//
//  Created on: 31.03.2018
//      Author: michael
//

#ifndef HAPTYPES_HPP_
#define HAPTYPES_HPP_


#include <Arduino.h>

enum HAP_TLV_TYPE {
    HAP_TLV_TYPE_METHOD,
    HAP_TLV_TYPE_IDENTIFIER,
    HAP_TLV_TYPE_SALT,
    HAP_TLV_TYPE_PUBLICKEY,
    HAP_TLV_TYPE_PROOF,
    HAP_TLV_TYPE_ENCRYPTED_DATA,
    HAP_TLV_TYPE_STATE,
    HAP_TLV_TYPE_ERROR,
    HAP_TLV_TYPE_RETRY_DELAY,
    HAP_TLV_TYPE_CERTIFICATE,
    HAP_TLV_TYPE_SIGNATURE,
    HAP_TLV_TYPE_PERMISSION,
    HAP_TLV_TYPE_FRAGMENT_DATA,
    HAP_TLV_TYPE_FRAGMENT_LAST,
    HAP_TLV_TYPE_SEPARATOR = 0xff,
};

enum HAP_TLV_ERROR_CODES {
    HAP_TLV_ERROR_UNKNOWN = 1,
    HAP_TLV_ERROR_AUTHENTICATION,
    HAP_TLV_ERROR_BACKOFF,
    HAP_TLV_ERROR_MAX_PEERS,
    HAP_TLV_ERROR_MAX_TRIES,
    HAP_TLV_ERROR_UNAVAILABLE,
    HAP_TLV_ERROR_BUSY,
};  

#endif /* HAPTYPES_HPP_ */