{
 "title": "Homekit",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname: $tag_accessory",
     "groupBy": [
      { "params": [ "accessory" ], "type": "tag" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "TemperatureSensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity & Moisture",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname: $tag_accessory",
     "groupBy": [
      { "params": [ "accessory" ], "type": "tag" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "MoistureSensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "$tag_hostname: $tag_accessory",
     "groupBy": [
      { "params": [ "accessory" ], "type": "tag" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "HumiditySensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Light",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "lux" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname: $tag_accessory",
     "groupBy": [
      { "params": [ "accessory" ], "type": "tag" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "LightSensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_hostname: $tag_accessory",
     "groupBy": [
      { "params": [ "accessory" ], "type": "tag" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "Battery",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}