/* Generated by BuildNumber Version 0.8 */

#ifndef HAPBUILDNUMBER_HPP_ 
#define HAPBUILDNUMBER_HPP_ 

#define HOMEKIT_VERSION_BUILD 142
#define HOMEKIT_VERSION_BUILD_STR "142" 

#endif /* HAPBUILDNUMBER_HPP_ */
