//
// HAPCharacteristicsBluetooth.hpp
// Homekit
//
//  Generated on: 23.09.2019
//

#ifndef HAPCHARACTERISTICSBLUETOOTH_HPP_
#define HAPCHARACTERISTICSBLUETOOTH_HPP_

#include <Arduino.h>

typedef enum {
    HAP_CHARACTERISTIC_BLUETOOTH_PAIR_SETUP             = 0x4C,
    HAP_CHARACTERISTIC_BLUETOOTH_PAIR_VERIFY            = 0x4E,
    HAP_CHARACTERISTIC_BLUETOOTH_PAIRING_FEATURE        = 0x4F,    
    HAP_CHARACTERISTIC_BLUETOOTH_PAIRINGS               = 0x50,
    HAP_CHARACTERISTIC_BLUETOOTH_SERVICE_INSTANCE_ID    = 0x51,
} HAP_CHARACTERISTIC_BLUETOOTH;




#endif /* HAPCHARACTERISTICSBLUETOOTH_HPP_ */
