// HAPCategories.hpp
// Homekit
//
//  Created on: 31.03.2018
//      Author: michael
//

#ifndef HAPCATEGORIES_HPP_
#define HAPCATEGORIES_HPP_

enum HAP_ACCESSORY_TYPE{
    HAP_ACCESSORY_TYPE_OTHER 				= 0,
    HAP_ACCESSORY_TYPE_BRIDGE				= 2,
    HAP_ACCESSORY_TYPE_FAN				 	= 3,
    HAP_ACCESSORY_TYPE_GARAGEDOOROPENER		= 4,
    HAP_ACCESSORY_TYPE_LIGHTBULB			= 5,
    HAP_ACCESSORY_TYPE_DOORLOCK		 		= 6,
    HAP_ACCESSORY_TYPE_OUTLET 				= 7,
    HAP_ACCESSORY_TYPE_SWITCH 				= 8,
    HAP_ACCESSORY_TYPE_THERMOSTAT	 		= 9,
    HAP_ACCESSORY_TYPE_SENSOR 				= 10,
    HAP_ACCESSORY_TYPE_ALARMSYSTEM 			= 11,
    HAP_ACCESSORY_TYPE_DOOR 				= 12,
    HAP_ACCESSORY_TYPE_WINDOW 				= 13,
    HAP_ACCESSORY_TYPE_WINDOWCOVER 			= 14,
    HAP_ACCESSORY_TYPE_PROGRAMMABLESWITCH 	= 15,
};


#endif /* HAPCATEGORIES_HPP_ */